//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasStantion.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fuels
    {
        public int Id { get; set; }
        public string FuelName { get; set; }
        public double Price { get; set; }
        public string FuelDescription { get; set; }
    }
}
