//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasStantion.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFeedbacks
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public int Stars { get; set; }
        public string Comment { get; set; }
        public bool IsShowOnMain { get; set; }
    }
}
